"""Command-line interface for PDF style learning and draft polishing."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from paper_style_ai.chunker import split_into_chunks
from paper_style_ai.config import ApiConfig
from paper_style_ai.pdf_reader import extract_from_directory, merge_pages
from paper_style_ai.polisher import PaperPolisher
from paper_style_ai.semantic_analyzer import SemanticAnalyzer, save_analysis
from paper_style_ai.style_template import load_template


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Learn academic-paper style from PDFs and polish drafts.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    learn = subparsers.add_parser("learn", help="Extract PDFs, chunk text, analyze style, and save template JSON.")
    learn.add_argument("--pdf-dir", required=True, type=Path, help="Directory containing English academic PDFs.")
    learn.add_argument("--output", required=True, type=Path, help="JSON file for chunks, analyses, and template.")
    learn.add_argument("--max-tokens", type=int, default=900, help="Approximate maximum tokens per chunk.")
    learn.add_argument("--overlap-tokens", type=int, default=120, help="Approximate overlap tokens between chunks.")
    learn.add_argument("--limit-chunks", type=int, default=None, help="Optional API-cost limit for analyzed chunks.")

    polish = subparsers.add_parser("polish", help="Polish a draft with a learned template.")
    polish.add_argument("--template", required=True, type=Path, help="JSON generated by the learn command.")
    polish.add_argument("--draft", required=True, type=Path, help="Plain-text draft to polish.")
    polish.add_argument("--output", type=Path, help="Optional JSON output path. Prints to stdout when omitted.")

    return parser


def main() -> None:
    args = build_parser().parse_args()
    config = ApiConfig.from_env()

    if args.command == "learn":
        pages = extract_from_directory(args.pdf_dir)
        corpus = merge_pages(pages)
        chunks = split_into_chunks(corpus, max_tokens=args.max_tokens, overlap_tokens=args.overlap_tokens)
        analyzer = SemanticAnalyzer(config)
        analyses = analyzer.analyze_chunks(chunks, limit=args.limit_chunks)
        template = analyzer.synthesize_style_template(analyses)
        save_analysis(args.output, chunks, analyses, template)
        print(f"Saved style analysis to {args.output}")
        return

    if args.command == "polish":
        template = load_template(args.template)
        draft = args.draft.read_text(encoding="utf-8")
        result = PaperPolisher(config).polish(draft, template)
        rendered = json.dumps(result, ensure_ascii=False, indent=2)
        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(rendered, encoding="utf-8")
            print(f"Saved polished draft to {args.output}")
        else:
            print(rendered)
        return


if __name__ == "__main__":
    main()
